<a href="https://colab.research.google.com/github/Jeanette22/Proyectos-de-datos-en-Colab/blob/Google-Colab--Poryectos/04-practica-python-datos/practica_python_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Para usar Python sin librerias, y sin instalar el programa ✨

In [ ]:
a = 1+1  #se le asigna una variable

In [ ]:
b="hola mundo!" #str con comillas a diferencia de los numeros

In [ ]:
a

2

In [ ]:
b

'hola mundo!'

In [ ]:
import pandas as pd

In [ ]:
d_star_wars=pd.DataFrame({'personaje': ['Luke Skywaker', 'C-3PO', 'Darth Vader'], 'altura':[172, 167, 202]}) #CREACIÓN DE TABLA !!!

In [ ]:
d_star_wars

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     202

In [ ]:
d_star_wars.dtypes #STR INT O DEC Cuando estemos trabajando en datos. Object representa una cadena de texto

personaje    object
altura        int64
dtype: object

In [ ]:
lista_personajes=['Luke Skywaker', 'C-3PO', 'Darth Vader'] #Creación de LISTAS

In [ ]:
lista_personajes

['Luke Skywaker', 'C-3PO', 'Darth Vader']

In [ ]:
lista_altura=[172, 167, 202]

In [ ]:
lista_altura

[172, 167, 202]

**Crear un DATAFRAME DESDE DOS LISTAS **

In [ ]:
# Crear un pandas dataframe basado en 2 listas #DICCIONARIO
d_sw=pd.DataFrame({'personaje': lista_personajes,  
                   'altura':lista_altura
                  })

In [ ]:
d_sw

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     202

**Filtrar datos en pandas. La lógica de la notación vectorial.**

In [ ]:
d_star_wars

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     202

In [ ]:
d_star_wars['personaje'] #filtrar una Columna

0    Luke Skywaker
1            C-3PO
2      Darth Vader
Name: personaje, dtype: object

In [ ]:
# d_star_wars.iloc[indice de fila/ indice de columna] PARA NOTACIONES MATRICIALES
d_star_wars.iloc[:, 0] # los dos puntos simboliza los slides (toda la fila)

0    Luke Skywaker
1            C-3PO
2      Darth Vader
Name: personaje, dtype: object

In [ ]:
d_star_wars.iloc[0, :] #Muestra toda la info de la columna 0

personaje    Luke Skywaker
altura                 172
Name: 0, dtype: object

In [ ]:
d_star_wars.loc[:, 'personaje'] # OTRA FORMA DE ACCEDER USANDO .LOC, Se pone Columna, en vez de : es equivalente a: d_star_wars.iloc[:, 0]

0    Luke Skywaker
1            C-3PO
2      Darth Vader
Name: personaje, dtype: object

In [ ]:
# índices para las columnas: #VER INDICES DE COLUMNAS
d_star_wars.columns

Index(['personaje', 'altura'], dtype='object')

In [ ]:
# índices de los registros
list(d_star_wars.index) #Hacemos Lista los indices numeros

[0, 1, 2]

In [ ]:
d_star_wars.loc[0, :] # es equivalente: d_star_wars.iloc[0, :] (porque el índice 0 es la posición y el nombre)

personaje    Luke Skywaker
altura                 172
Name: 0, dtype: object

In [ ]:
# acceder a 1 elemento CON LOC 
d_star_wars.loc[0, 'altura']

172

In [ ]:
d_star_wars.loc[1, 'altura']

167

**¿Cómo reemplazar valores en pandas data frame basado en una condición?**

![](https://shanelynnwebsite-mid9n9g1q9y8tt.netdna-ssl.com/wp-content/uploads/2016/10/Pandas-selections-and-indexing-768x549.png)

In [ ]:
d_star_wars

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     202

In [ ]:
d_star_wars.iloc[0:2, 0] #SLICES  #PARA VER LOS DOS PRIMEROS REGISTROS

0    Luke Skywaker
1            C-3PO
Name: personaje, dtype: object

In [ ]:
# nos devuelve todo PORQUE ES UN DATAFRAME CHICA 
d_star_wars.iloc[0:3, 0:2]

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     202

#REEMPLAZAR VALORES

In [ ]:
# otra manera de filtrar vectorialmente de comparacion == #ACA VEMOS CUANDO COINCIDE LOS VALORES QUE ES LA FILA 2: POR ESO TRUE
d_star_wars['personaje']=='Darth Vader'

0    False
1    False
2     True
Name: personaje, dtype: bool

In [ ]:
# ¿Cómo le cambiamos la altura a Darth Vader?
v_flag=d_star_wars['personaje']=='Darth Vader'

In [ ]:
d_star_wars.loc[v_flag, 'altura']

2    202
Name: altura, dtype: int64

In [ ]:
d_star_wars.loc[v_flag, 'altura'] = 185 #Suponiendo que no sabemos donde esta ese personaje, por eso la varibale v_flag,

In [ ]:
d_star_wars

       personaje  altura
0  Luke Skywaker     172
1          C-3PO     167
2    Darth Vader     185

In [ ]:
# haciendo todo en la misma linea
d_star_wars.loc[ d_star_wars['personaje']=='Luke Skywaker', 'altura']=200

In [ ]:
d_star_wars

       personaje  altura
0  Luke Skywaker     200
1          C-3PO     167
2    Darth Vader     185

# **Cargar Archivos del Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

data_turismo=pd.read_csv("/content/drive/MyDrive/saldo-turistas-serie.csv")

In [ ]:
data_turismo.head ()

  indice_tiempo medio_de_transporte      pais  balanza
0       2016-01               Aérea   Bolivia   3635.9
1       2016-01               Aérea    Brasil -66768.5
2       2016-01               Aérea     Chile -11200.7
3       2016-01               Aérea  Paraguay   1996.4
4       2016-01               Aérea   Uruguay -12748.3

In [ ]:
data_turismo.tail()

     indice_tiempo medio_de_transporte              pais  balanza
1696       2021-03    Fluvial/Marítima           Uruguay  -4172.0
1697       2021-03    Fluvial/Marítima   EE.UU. y Canadá      6.0
1698       2021-03    Fluvial/Marítima  Resto de América      4.0
1699       2021-03    Fluvial/Marítima            Europa     15.0
1700       2021-03    Fluvial/Marítima   Resto del mundo      4.0

In [ ]:
data_turismo.shape

(1701, 4)

In [ ]:
from google.colab.data_table import DataTable

DataTable(data_turismo)

**NON ES EQUIVALENTE A NaN #cuando se hablan de datos nulos **

In [ ]:
!pip install funpymodeling

Collecting funpymodeling
  Downloading funpymodeling-0.1.7-py3-none-any.whl (6.4 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (1.1.5)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (3.10.0.2)
Requirement already satisfied: sklearn<0.1,>=0.0 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (0.0)
Collecting seaborn<0.11.0,>=0.10.1
  Downloading seaborn-0.10.1-py3-none-any.whl (215 kB)
     |████████████████████████████████| 215 kB 5.4 MB/s
Requirement already satisfied: numpy<2.0.0,>=1.18.5 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (1.19.5)
Requirement already satisfied: matplotlib<4.0.0,>=3.2.2 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (3.2.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.3.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (3.0.6)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.5->funpymodeling) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.15.0)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from seaborn<0.11.0,>=0.10.1->funpymodeling) (1.4.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn<0.1,>=0.0->funpymodeling) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn<0.1,>=0.0->funpymodeling) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn<0.1,>=0.0->funpymodeling) (1.1.0)
Installing collected packages: seaborn, funpymodeling
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
Successfully installed funpymodeling-0.1.7 seaborn-0.10.1

In [ ]:
data_turismo.isna () #veo por True o false valores nulos

      indice_tiempo  medio_de_transporte   pais  balanza
0             False                False  False    False
1             False                False  False    False
2             False                False  False    False
3             False                False  False    False
4             False                False  False    False
...             ...                  ...    ...      ...
1696          False                False  False    False
1697          False                False  False    False
1698          False                False  False    False
1699          False                False  False    False
1700          False                False  False    False

[1701 rows x 4 columns]

In [ ]:
# obtener nulos de una columna
data_turismo[data_turismo['indice_tiempo'].isna ()]

Empty DataFrame
Columns: [indice_tiempo, medio_de_transporte, pais, balanza]
Index: []

In [ ]:
from funpymodeling.exploratory import status

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
status (data_turismo)

              variable  q_nan  p_nan  q_zeros   p_zeros  unique     type
0        indice_tiempo      0    0.0        0  0.000000      63   object
1  medio_de_transporte      0    0.0        0  0.000000       3   object
2                 pais      0    0.0        0  0.000000       9   object
3              balanza      0    0.0       92  0.054086    1541  float64

# **Reemplazo de Valores Nulos ** texto en negrita

In [ ]:
import numpy as np

variable categórica / object

In [ ]:
values={'indice_tiempo': 'nulo_indice', 'balanza': 'nulo_balanza'}

data_turismo.fillna(value=values)

     indice_tiempo medio_de_transporte              pais  balanza
0          2016-01               Aérea           Bolivia   3635.9
1          2016-01               Aérea            Brasil -66768.5
2          2016-01               Aérea             Chile -11200.7
3          2016-01               Aérea          Paraguay   1996.4
4          2016-01               Aérea           Uruguay -12748.3
...            ...                 ...               ...      ...
1696       2021-03    Fluvial/Marítima           Uruguay  -4172.0
1697       2021-03    Fluvial/Marítima   EE.UU. y Canadá      6.0
1698       2021-03    Fluvial/Marítima  Resto de América      4.0
1699       2021-03    Fluvial/Marítima            Europa     15.0
1700       2021-03    Fluvial/Marítima   Resto del mundo      4.0

[1701 rows x 4 columns]

In [ ]:
# remplazo en el mismo data frame
data_turismo.fillna(value=values, inplace=True)

In [ ]:
data_turismo

     indice_tiempo medio_de_transporte              pais  balanza
0          2016-01               Aérea           Bolivia   3635.9
1          2016-01               Aérea            Brasil -66768.5
2          2016-01               Aérea             Chile -11200.7
3          2016-01               Aérea          Paraguay   1996.4
4          2016-01               Aérea           Uruguay -12748.3
...            ...                 ...               ...      ...
1696       2021-03    Fluvial/Marítima           Uruguay  -4172.0
1697       2021-03    Fluvial/Marítima   EE.UU. y Canadá      6.0
1698       2021-03    Fluvial/Marítima  Resto de América      4.0
1699       2021-03    Fluvial/Marítima            Europa     15.0
1700       2021-03    Fluvial/Marítima   Resto del mundo      4.0

[1701 rows x 4 columns]

## Imputación de nulos para variables numéricas

In [ ]:
# Obtención del promedio, y luego imputamos una columna
data_turismo['balanza'].mean()

-9431.563198118745

In [ ]:
data_turismo['balanza']=data_turismo['balanza'].fillna(data_turismo['balanza'].mean())

data_turismo

     indice_tiempo medio_de_transporte              pais  balanza
0          2016-01               Aérea           Bolivia   3635.9
1          2016-01               Aérea            Brasil -66768.5
2          2016-01               Aérea             Chile -11200.7
3          2016-01               Aérea          Paraguay   1996.4
4          2016-01               Aérea           Uruguay -12748.3
...            ...                 ...               ...      ...
1696       2021-03    Fluvial/Marítima           Uruguay  -4172.0
1697       2021-03    Fluvial/Marítima   EE.UU. y Canadá      6.0
1698       2021-03    Fluvial/Marítima  Resto de América      4.0
1699       2021-03    Fluvial/Marítima            Europa     15.0
1700       2021-03    Fluvial/Marítima   Resto del mundo      4.0

[1701 rows x 4 columns]

# **EJERCICIOS **

In [ ]:
list_valores1 = [1,2,3,4,5]
list_valores2 = ["a", "b", "c", "d", "e"]

In [ ]:
list_valores1

[1, 2, 3, 4, 5]

In [ ]:
list_valores2

['a', 'b', 'c', 'd', 'e']

In [ ]:
import pandas as pd

In [ ]:
d_test = pd.DataFrame ({'columna1': list_valores1,
                        'columna2': list_valores2
                      })

In [ ]:
d_test

   columna1 columna2
0         1        a
1         2        b
2         3        c
3         4        d
4         5        e

In [ ]:
d_hd = pd.read_csv ("https://raw.githubusercontent.com/pablo14/datasets/main/heart_disease/heart_disease.csv")

In [ ]:
d_hd

     age  gender  ...  exter_angina  has_heart_disease
0     63    male  ...             0                 no
1     67    male  ...             1                yes
2     67    male  ...             1                yes
3     37    male  ...             0                 no
4     41  female  ...             0                 no
..   ...     ...  ...           ...                ...
298   45    male  ...             0                yes
299   68    male  ...             0                yes
300   57    male  ...             1                yes
301   57  female  ...             0                yes
302   38    male  ...             0                 no

[303 rows x 16 columns]

In [ ]:
d_hd ['age'], ['has_heart_disease'] # Imprimir la variable `age` y `has_heart_disease` al mismo tiempo. No usar loc ni iloc.

(0      63
 1      67
 2      67
 3      37
 4      41
        ..
 298    45
 299    68
 300    57
 301    57
 302    38
 Name: age, Length: 303, dtype: int64, ['has_heart_disease'])

In [ ]:
from google.colab.data_table import DataTable

DataTable(d_hd)

In [ ]:
d_hd.head()

   age  gender  ...  exter_angina  has_heart_disease
0   63    male  ...             0                 no
1   67    male  ...             1                yes
2   67    male  ...             1                yes
3   37    male  ...             0                 no
4   41  female  ...             0                 no

[5 rows x 16 columns]

In [ ]:
d_hd.tail()

     age  gender  ...  exter_angina  has_heart_disease
298   45    male  ...             0                yes
299   68    male  ...             0                yes
300   57    male  ...             1                yes
301   57  female  ...             0                yes
302   38    male  ...             0                 no

[5 rows x 16 columns]

In [ ]:
d_hd.loc[:,'has_heart_disease'] #Acceder con loc a la columna has_heart_disease, y mostrar todos los registros

0       no
1      yes
2      yes
3       no
4       no
      ...
298    yes
299    yes
300    yes
301    yes
302     no
Name: has_heart_disease, Length: 303, dtype: object

In [ ]:
d_hd.loc[:,'has_heart_disease', 2]

IndexingError: ignored

In [ ]:
# 3.6) Usar iloc para obtener las primeras 3 columnas, y 5 registros

In [ ]:
d_hd.iloc[0: 3, 5] #Usar iloc para obtener las primeras 3 columnas, y 5 registros

0    1
1    0
2    0
Name: fasting_blood_sugar, dtype: int64

In [ ]:
!pip install funpymodeling

Collecting funpymodeling
  Downloading funpymodeling-0.1.7-py3-none-any.whl (6.4 kB)
Requirement already satisfied: sklearn<0.1,>=0.0 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (0.0)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (3.10.0.2)
Collecting seaborn<0.11.0,>=0.10.1
  Downloading seaborn-0.10.1-py3-none-any.whl (215 kB)
     |████████████████████████████████| 215 kB 27.6 MB/s
Requirement already satisfied: pandas<2.0.0,>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (1.1.5)
Requirement already satisfied: matplotlib<4.0.0,>=3.2.2 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (3.2.2)
Requirement already satisfied: numpy<2.0.0,>=1.18.5 in /usr/local/lib/python3.7/dist-packages (from funpymodeling) (1.19.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.3.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.5->funpymodeling) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.15.0)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from seaborn<0.11.0,>=0.10.1->funpymodeling) (1.4.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn<0.1,>=0.0->funpymodeling) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn<0.1,>=0.0->funpymodeling) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn<0.1,>=0.0->funpymodeling) (1.1.0)
Installing collected packages: seaborn, funpymodeling
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
Successfully installed funpymodeling-0.1.7 seaborn-0.10.1

In [ ]:
from funpymodeling.exploratory import status

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
# 4.3) ¿Qué variables tienen nulos?  (usar status) 
status (d_hd)

                  variable  q_nan     p_nan  q_zeros   p_zeros  unique     type
0                      age      0  0.000000        0  0.000000      41    int64
1                   gender      0  0.000000        0  0.000000       2   object
2               chest_pain      0  0.000000        0  0.000000       4    int64
3   resting_blood_pressure      0  0.000000        0  0.000000      50    int64
4        serum_cholestoral      0  0.000000        0  0.000000     152    int64
5      fasting_blood_sugar      0  0.000000      258  0.851485       2    int64
6          resting_electro      0  0.000000      151  0.498350       3    int64
7           max_heart_rate      0  0.000000        0  0.000000      91    int64
8              exer_angina      0  0.000000      204  0.673267       2    int64
9                  oldpeak      0  0.000000       99  0.326733      40  float64
10                   slope      0  0.000000        0  0.000000       3    int64
11       num_vessels_flour      4  0.013201      176  0.580858       4  float64
12                    thal      2  0.006601        0  0.000000       3  float64
13  heart_disease_severity      0  0.000000      164  0.541254       5    int64
14            exter_angina      0  0.000000      204  0.673267       2    int64
15       has_heart_disease      0  0.000000        0  0.000000       2   object

In [ ]:
#Devolver un data frame con todos los registros que tienen NaN en la variable "thal".

In [ ]:
import numpy as np

In [ ]:
thal=pd.Series([1,2,3, np.NaN])

In [ ]:
thal

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [ ]:
d_ ['hair_color'].isna()

NameError: ignored